### Post "Hello!"
POST http://localhost:8080/
Content-Type: application/json

{
  "title": "The Return of the King",
  "description": "The forces of good and evil converge in a final battle for the fate of Middle-earth, as Frodo and Sam draw closer to their goal of destroying the One Ring."
}

### Post "Bonjour!"

POST http://localhost:8080/
Content-Type: application/json

{
  "title": "Bonjour!",
  "description": "Fuck Off"
}

### Post "Privet!"

POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Privet!"
}

### Get all the messages
GET http://localhost:8080/